from pathlib import Path

p = Path('src/app/admin/page.tsx')
s = p.read_text()

s = s.replace("import { ImageUpload } from '@/components/ui/ImageUpload';", "import { ImageUpload } from '@/components/ui/ImageUpload';\nimport { ProductImageManager, type ProductImageDraft } from '@/components/admin/ProductImageManager';")
s = s.replace("    regularPrice: 0,\n    price: 0,\n    img: '',\n  });", "    price: 0,\n    offerActive: false,\n    offerPrice: 0,\n    img: '',\n  });\n  const [productImages, setProductImages] = useState<ProductImageDraft[]>([]);")
s = s.replace("    if (!prodForm.name || prodForm.price <= 0) {\n      showToast('Campos incompletos', 'Ingresa nombre y precio válido');", "    if (!prodForm.name || prodForm.price <= 0 || (prodForm.offerActive && (prodForm.offerPrice <= 0 || prodForm.offerPrice >= prodForm.price))) {\n      showToast('Revisa los precios', prodForm.offerActive ? 'El precio de oferta debe ser mayor a 0 y menor que el precio regular' : 'Ingresa nombre y precio regular válido');")
s = s.replace("        category: prodForm.category, delivery: prodForm.delivery, regular_price: prodForm.regularPrice,\n        price: prodForm.price, img: prodForm.img, updated_at: new Date().toISOString() };", "        category: prodForm.category, delivery: prodForm.delivery, regular_price: prodForm.price,\n        price: prodForm.price, offer_active: prodForm.offerActive, offer_price: prodForm.offerActive ? prodForm.offerPrice : null,\n        img: productImages[0]?.url || prodForm.img || '', updated_at: new Date().toISOString() };")
s = s.replace("      if (error) throw error;\n      setProducts(previous", "      if (error) throw error;\n      if (data?.id) {\n        const { error: imageDeleteError } = await supabase.from('product_images').delete().eq('product_id', data.id);\n        if (imageDeleteError) throw imageDeleteError;\n        if (productImages.length) {\n          const rows = productImages.map((image, index) => ({ product_id: data.id, url: image.url, sort_order: index, is_primary: index === 0 }));\n          const { error: imageInsertError } = await supabase.from('product_images').insert(rows);\n          if (imageInsertError) throw imageInsertError;\n        }\n      }\n      setProducts(previous", 1)
s = s.replace("      regularPrice: p.regular_price ?? p.regularPrice ?? p.price,\n      price: p.price,\n      img: p.img,\n    });\n    setProductModalOpen(true);", "      price: p.regular_price ?? p.regularPrice ?? p.price,\n      offerActive: !!p.offer_active,\n      offerPrice: p.offer_price ?? 0,\n      img: p.img || '',\n    });\n    const supabase = getSupabaseBrowserClient();\n    if (supabase) {\n      void supabase.from('product_images').select('id,url,sort_order,is_primary').eq('product_id', p.id).order('sort_order').then(({ data }) => {\n        const loaded = (data || []).map((image: any, index: number) => ({ id: image.id, url: image.url, sort_order: image.sort_order ?? index, is_primary: !!image.is_primary }));\n        setProductImages(loaded.length ? loaded : (p.img ? [{ url: p.img, sort_order: 0, is_primary: true }] : []));\n      });\n    } else setProductImages(p.img ? [{ url: p.img, sort_order: 0, is_primary: true }] : []);\n    setProductModalOpen(true);")
s = s.replace("                        regularPrice: 0,\n                        price: 0,\n                        img: '',\n                      });", "                        price: 0,\n                        offerActive: false,\n                        offerPrice: 0,\n                        img: '',\n                      });\n                      setProductImages([]);")

modal = s.index('{/* Product Modal */}')
first_grid = s.index('              <div className="grid grid-cols-2 gap-3">', modal)
price_grid = s.index('              <div className="grid grid-cols-2 gap-3">', first_grid + 10)
price_end = s.index('\n\n              <div>\n                <label className="block text-slate-400 font-bold mb-1">Descripción del producto</label>', price_grid)
price_block = '''              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 items-end">\n                <div>\n                  <label className="block text-slate-400 font-bold mb-1">Precio Regular (S/)</label>\n                  <input type="number" min="0.01" step="0.01" required value={prodForm.price}\n                    onChange={(e) => setProdForm({ ...prodForm, price: parseFloat(e.target.value) || 0 })}\n                    className="w-full bg-slate-800 border border-slate-700 text-white rounded-xl px-3 py-2 focus:outline-none focus:border-amber-500" />\n                </div>\n                <label className="flex items-center gap-2 rounded-xl border border-slate-700 bg-slate-800/40 px-3 py-2.5 cursor-pointer">\n                  <input type="checkbox" checked={prodForm.offerActive} onChange={e => setProdForm({ ...prodForm, offerActive: e.target.checked, offerPrice: e.target.checked ? prodForm.offerPrice : 0 })} className="h-4 w-4 accent-amber-500" />\n                  <span className="font-bold text-white">Activar oferta</span>\n                </label>\n              </div>\n\n              {prodForm.offerActive && <div>\n                <label className="block text-slate-400 font-bold mb-1">Precio Oferta (S/)</label>\n                <input type="number" min="0.01" step="0.01" required value={prodForm.offerPrice || ''}\n                  onChange={e => setProdForm({ ...prodForm, offerPrice: parseFloat(e.target.value) || 0 })}\n                  className="w-full bg-slate-800 border border-slate-700 text-white rounded-xl px-3 py-2 focus:outline-none focus:border-amber-500" />\n              </div>}'''
s = s[:price_grid] + price_block + s[price_end:]

image_start = s.index('<ImageUpload', s.index('{/* Product Modal */}'))
image_end = s.index('\n              </div>', image_start)
s = s[:image_start] + '<ProductImageManager images={productImages} onChange={setProductImages} onBusy={setUploading} />' + s[image_end:]

p.write_text(s)
