'use client';

import { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import { getSupabaseBrowserClient } from '@/lib/supabase/client';

type Product = { id:string; name:string; description:string; category:string; delivery:string; regular_price:number; price:number; img:string; active?:boolean };
type ProductImage = { id?:string; url:string; storage_path?:string|null; sort_order:number; is_primary:boolean };
type Ticket = { id:string; ticket_code:string; origen:string; cliente:string; telefono:string; detalle:string; total:number; estado:string; tipo?:string|null; notas_admin?:string|null; created_at?:string };

const blankProduct = { name:'', description:'', category:'Perfumes', delivery:'En stock en Lima', regular_price:0, price:0, active:true };
const blankTicket = { origen:'Web', cliente:'', telefono:'', detalle:'', total:0, estado:'Pendiente', tipo:'whatsapp_manual', notas_admin:'' };
const statuses = ['Pendiente','Cotizado','Confirmado y pagado','Comprado en USA','En camino a Perú','Listo para entrega','Entregado','Cancelado'];

export default function CrmPage(){
  const supabase = getSupabaseBrowserClient();
  const [ready,setReady]=useState(false); const [logged,setLogged]=useState(false); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState('');
  const [tab,setTab]=useState<'products'|'orders'>('products'); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState('');
  const [products,setProducts]=useState<Product[]>([]); const [categories,setCategories]=useState<string[]>([]); const [productOpen,setProductOpen]=useState(false); const [editingProduct,setEditingProduct]=useState<Product|null>(null); const [productForm,setProductForm]=useState(blankProduct); const [images,setImages]=useState<ProductImage[]>([]);
  const [tickets,setTickets]=useState<Ticket[]>([]); const [ticketOpen,setTicketOpen]=useState(false); const [editingTicket,setEditingTicket]=useState<Ticket|null>(null); const [ticketForm,setTicketForm]=useState(blankTicket);

  useEffect(()=>{ if(!supabase){setReady(true);return;} supabase.auth.getSession().then(({data})=>{setLogged(!!data.session?.user);setReady(true);}); const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setLogged(!!s?.user)); return()=>subscription.unsubscribe(); },[]);
  useEffect(()=>{ if(logged) void refreshAll(); },[logged]);

  async function refreshAll(){ if(!supabase)return; const [p,c,t]=await Promise.all([
    supabase.from('products').select('*').order('created_at',{ascending:false}),
    supabase.from('categories').select('name').eq('active',true).order('display_order'),
    supabase.from('tickets').select('*').order('created_at',{ascending:false})
  ]); if(p.error||t.error){setNotice('No se pudo leer toda la información. Verifica permisos de Supabase.');} setProducts((p.data||[]) as Product[]); setCategories((c.data||[]).map(x=>x.name)); setTickets((t.data||[]) as Ticket[]); }

  async function login(e:FormEvent){e.preventDefault(); if(!supabase)return; setBusy(true);setError(''); const {error}=await supabase.auth.signInWithPassword({email:email.trim().toLowerCase(),password}); if(error)setError(error.message); setBusy(false);}
  async function logout(){await supabase?.auth.signOut();}

  async function openProduct(p?:Product){ setEditingProduct(p||null); setProductForm(p?{name:p.name,description:p.description||'',category:p.category,delivery:p.delivery,regular_price:Number(p.regular_price||0),price:Number(p.price||0),active:p.active!==false}:blankProduct); if(p&&supabase){const {data}=await supabase.from('product_images').select('*').eq('product_id',p.id).order('sort_order'); setImages((data||[]) as ProductImage[]);} else setImages([]); setProductOpen(true); }

  async function uploadImages(files:FileList|null){ if(!files||!supabase)return; const remaining=6-images.length; const selected=Array.from(files).slice(0,remaining); if(!selected.length){setNotice('Máximo 6 imágenes por producto.');return;} setBusy(true); try{ const added:ProductImage[]=[]; for(const file of selected){ if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024) throw new Error('Solo JPG, PNG o WEBP de hasta 5 MB.'); const ext=file.type==='image/png'?'png':file.type==='image/webp'?'webp':'jpg'; const path=`catalog/${crypto.randomUUID()}.${ext}`; const {error}=await supabase.storage.from('storebass-media').upload(path,file,{contentType:file.type,upsert:false}); if(error)throw error; const {data}=supabase.storage.from('storebass-media').getPublicUrl(path); added.push({url:data.publicUrl,storage_path:path,sort_order:images.length+added.length,is_primary:images.length+added.length===0}); } setImages(prev=>[...prev,...added]); }catch(e:any){setNotice(e.message||'No se pudieron subir las imágenes.');}finally{setBusy(false);} }
  function removeImage(index:number){ setImages(prev=>{const next=prev.filter((_,i)=>i!==index).map((x,i)=>({...x,sort_order:i,is_primary:i===0}));return next;}); }
  function moveImage(index:number,dir:-1|1){setImages(prev=>{const target=index+dir;if(target<0||target>=prev.length)return prev;const next=[...prev];[next[index],next[target]]=[next[target],next[index]];return next.map((x,i)=>({...x,sort_order:i,is_primary:i===0}));});}

  async function saveProduct(e:FormEvent){e.preventDefault();if(!supabase||busy)return;if(!productForm.name.trim()||productForm.price<=0||images.length===0){setNotice('Nombre, precio y al menos una imagen son obligatorios.');return;}setBusy(true);try{
    const values={...productForm,name:productForm.name.trim(),description:productForm.description.trim(),img:images[0].url,updated_at:new Date().toISOString()};
    let productId=editingProduct?.id; if(productId){const {error}=await supabase.from('products').update(values).eq('id',productId);if(error)throw error;}else{const {data,error}=await supabase.from('products').insert(values).select('id').single();if(error)throw error;productId=data.id;}
    const {error:delError}=await supabase.from('product_images').delete().eq('product_id',productId!); if(delError)throw delError;
    const {error:imgError}=await supabase.from('product_images').insert(images.map((x,i)=>({product_id:productId,url:x.url,storage_path:x.storage_path||null,sort_order:i,is_primary:i===0}))); if(imgError)throw imgError;
    setProductOpen(false);setNotice(editingProduct?'Producto actualizado correctamente.':'Producto creado correctamente.');await refreshAll();
  }catch(e:any){setNotice(`No se pudo guardar: ${e.message||'error de Supabase'}`);}finally{setBusy(false);} }

  async function deleteProduct(p:Product){if(!supabase||!confirm(`¿Eliminar ${p.name}?`))return;setBusy(true);const {error}=await supabase.from('products').delete().eq('id',p.id);setBusy(false);if(error){setNotice(`No se pudo eliminar: ${error.message}`);return;}setNotice('Producto eliminado.');await refreshAll();}

  function openTicket(t?:Ticket){setEditingTicket(t||null);setTicketForm(t?{origen:t.origen,cliente:t.cliente,telefono:t.telefono,detalle:t.detalle,total:Number(t.total||0),estado:t.estado,tipo:t.tipo||'whatsapp_manual',notas_admin:t.notas_admin||''}:blankTicket);setTicketOpen(true);}
  async function saveTicket(e:FormEvent){e.preventDefault();if(!supabase||busy)return;setBusy(true);try{if(editingTicket){const {error}=await supabase.from('tickets').update({...ticketForm,updated_at:new Date().toISOString()}).eq('id',editingTicket.id);if(error)throw error;}else{const {error}=await supabase.rpc('fn_create_ticket',{p_origen:ticketForm.origen,p_cliente:ticketForm.cliente,p_telefono:ticketForm.telefono,p_detalle:ticketForm.detalle,p_total:ticketForm.total,p_estado:ticketForm.estado,p_tipo:ticketForm.tipo,p_items:[]});if(error)throw error;}setTicketOpen(false);setNotice(editingTicket?'Pedido actualizado.':'Pedido ingresado.');await refreshAll();}catch(e:any){setNotice(`No se pudo guardar el pedido: ${e.message}`);}finally{setBusy(false);}}
  async function deleteTicket(t:Ticket){if(!supabase||!confirm(`¿Eliminar el ticket ${t.ticket_code}?`))return;setBusy(true);const {error}=await supabase.from('tickets').delete().eq('id',t.id);setBusy(false);if(error){setNotice(`No se pudo eliminar: ${error.message}`);return;}setNotice('Pedido eliminado.');await refreshAll();}

  if(!ready)return <main className="min-h-screen bg-slate-950 text-white grid place-items-center">Conectando con Supabase…</main>;
  if(!logged)return <main className="min-h-screen bg-slate-950 text-white grid place-items-center p-4"><form onSubmit={login} className="w-full max-w-sm bg-slate-900 border border-slate-800 rounded-3xl p-7 space-y-4"><h1 className="text-2xl font-black">STORE <span className="text-amber-500">BASS</span> CRM</h1><p className="text-xs text-slate-400">Acceso administrativo mediante Supabase Auth.</p>{error&&<p className="text-xs text-rose-400">{error}</p>}<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="Correo administrador" className="w-full bg-slate-800 border border-slate-700 rounded-xl px-3 py-3"/><input type="password" required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Contraseña" className="w-full bg-slate-800 border border-slate-700 rounded-xl px-3 py-3"/><button disabled={busy} className="w-full bg-amber-500 text-slate-950 font-black rounded-xl py-3">Ingresar</button><Link href="/" className="block text-center text-xs text-slate-400">Volver a la tienda</Link></form></main>;

  return <main className="min-h-screen bg-slate-950 text-white p-4 sm:p-6"><div className="max-w-7xl mx-auto space-y-5">
    <header className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><h1 className="text-2xl font-black">STORE <span className="text-amber-500">BASS</span> CRM</h1><p className="text-xs text-slate-400">Gestión conectada directamente a Supabase</p></div><div className="flex gap-2"><Link href="/admin" className="px-3 py-2 rounded-xl bg-slate-800 text-xs font-bold">Panel general</Link><button onClick={logout} className="px-3 py-2 rounded-xl bg-rose-950 text-rose-300 text-xs font-bold">Cerrar sesión</button></div></header>
    {notice&&<div className="p-3 rounded-xl border border-amber-500/30 bg-amber-500/10 text-amber-200 text-xs flex justify-between"><span>{notice}</span><button onClick={()=>setNotice('')}>×</button></div>}
    <nav className="flex gap-2"><button onClick={()=>setTab('products')} className={`px-4 py-2 rounded-xl text-sm font-bold ${tab==='products'?'bg-amber-500 text-slate-950':'bg-slate-900'}`}>Productos ({products.length})</button><button onClick={()=>setTab('orders')} className={`px-4 py-2 rounded-xl text-sm font-bold ${tab==='orders'?'bg-amber-500 text-slate-950':'bg-slate-900'}`}>Pedidos ({tickets.length})</button></nav>

    {tab==='products'&&<section className="space-y-4"><div className="flex justify-between items-center"><div><h2 className="font-black">Catálogo y galería</h2><p className="text-xs text-slate-400">Crear, modificar, actualizar y eliminar productos; hasta 6 fotos por producto.</p></div><button onClick={()=>void openProduct()} className="bg-amber-500 text-slate-950 font-black px-4 py-2.5 rounded-xl text-xs">+ Nuevo producto</button></div><div className="overflow-x-auto rounded-2xl border border-slate-800"><table className="w-full min-w-[760px] text-xs"><thead className="bg-slate-900 text-slate-400"><tr><th className="p-3 text-left">Producto</th><th>Categoría</th><th>Precio</th><th>Entrega</th><th className="text-right p-3">Acciones</th></tr></thead><tbody>{products.map(p=><tr key={p.id} className="border-t border-slate-800"><td className="p-3"><div className="flex items-center gap-3"><img src={p.img} alt="" className="w-12 h-12 rounded-lg object-cover bg-slate-900"/><div><b>{p.name}</b><p className="text-slate-500 max-w-md truncate">{p.description}</p></div></div></td><td className="text-center">{p.category}</td><td className="text-center font-black text-amber-400">S/ {Number(p.price).toFixed(2)}</td><td className="text-center">{p.delivery}</td><td className="p-3 text-right space-x-2"><button onClick={()=>void openProduct(p)} className="px-3 py-2 bg-slate-800 rounded-lg">Editar</button><button disabled={busy} onClick={()=>void deleteProduct(p)} className="px-3 py-2 bg-rose-950 text-rose-300 rounded-lg">Eliminar</button></td></tr>)}</tbody></table></div></section>}

    {tab==='orders'&&<section className="space-y-4"><div className="flex justify-between items-center"><div><h2 className="font-black">CRM de pedidos</h2><p className="text-xs text-slate-400">Ingreso, edición, actualización de estado y eliminación sincronizados con Supabase.</p></div><button onClick={()=>openTicket()} className="bg-amber-500 text-slate-950 font-black px-4 py-2.5 rounded-xl text-xs">+ Ingresar pedido</button></div><div className="overflow-x-auto rounded-2xl border border-slate-800"><table className="w-full min-w-[900px] text-xs"><thead className="bg-slate-900 text-slate-400"><tr><th className="p-3 text-left">Ticket</th><th>Cliente</th><th>Detalle</th><th>Total</th><th>Estado</th><th className="text-right p-3">Acciones</th></tr></thead><tbody>{tickets.map(t=><tr key={t.id} className="border-t border-slate-800"><td className="p-3 font-mono text-amber-400">{t.ticket_code}</td><td className="text-center"><b>{t.cliente}</b><div className="text-slate-500">{t.telefono}</div></td><td className="p-3 max-w-sm truncate">{t.detalle}</td><td className="text-center font-black">S/ {Number(t.total).toFixed(2)}</td><td className="text-center"><span className="px-2 py-1 rounded-full bg-blue-500/10 text-blue-300">{t.estado}</span></td><td className="p-3 text-right space-x-2"><button onClick={()=>openTicket(t)} className="px-3 py-2 bg-slate-800 rounded-lg">Modificar</button><button disabled={busy} onClick={()=>void deleteTicket(t)} className="px-3 py-2 bg-rose-950 text-rose-300 rounded-lg">Eliminar</button></td></tr>)}</tbody></table></div></section>}
  </div>

  {productOpen&&<div className="fixed inset-0 z-50 bg-slate-950/85 p-4 overflow-y-auto"><form onSubmit={saveProduct} className="max-w-2xl mx-auto my-4 bg-slate-900 border border-slate-800 rounded-3xl p-6 space-y-4"><div className="flex justify-between"><h3 className="font-black text-lg">{editingProduct?'Modificar producto':'Nuevo producto'}</h3><button type="button" onClick={()=>setProductOpen(false)}>✕</button></div><div className="grid sm:grid-cols-2 gap-3"><input required value={productForm.name} onChange={e=>setProductForm({...productForm,name:e.target.value})} placeholder="Nombre" className="bg-slate-800 border border-slate-700 rounded-xl p-3"/><select value={productForm.category} onChange={e=>setProductForm({...productForm,category:e.target.value})} className="bg-slate-800 border border-slate-700 rounded-xl p-3">{(categories.length?categories:['Perfumes','Tecnología','Moda','Suplementos']).map(c=><option key={c}>{c}</option>)}</select><input type="number" step="0.01" value={productForm.regular_price} onChange={e=>setProductForm({...productForm,regular_price:Number(e.target.value)})} placeholder="Precio regular" className="bg-slate-800 border border-slate-700 rounded-xl p-3"/><input required type="number" step="0.01" value={productForm.price} onChange={e=>setProductForm({...productForm,price:Number(e.target.value)})} placeholder="Precio oferta" className="bg-slate-800 border border-slate-700 rounded-xl p-3"/><select value={productForm.delivery} onChange={e=>setProductForm({...productForm,delivery:e.target.value})} className="sm:col-span-2 bg-slate-800 border border-slate-700 rounded-xl p-3"><option>En stock en Lima</option><option>Llega el 29 de Octubre</option><option>Últimos cupos</option><option>Solo a pedido</option><option>Agotado</option></select></div><textarea rows={4} value={productForm.description} onChange={e=>setProductForm({...productForm,description:e.target.value})} placeholder="Descripción e información adicional" className="w-full bg-slate-800 border border-slate-700 rounded-xl p-3"/>
  <div className="rounded-2xl border border-slate-700 p-4 space-y-3"><div className="flex justify-between"><div><b>Galería del producto</b><p className="text-[11px] text-slate-400">Hasta 6 fotos. La primera será la portada.</p></div><label className={`px-3 py-2 rounded-xl bg-amber-500 text-slate-950 text-xs font-black cursor-pointer ${images.length>=6?'opacity-50 pointer-events-none':''}`}>+ Subir fotos<input type="file" multiple accept="image/jpeg,image/png,image/webp" className="hidden" onChange={e=>{void uploadImages(e.target.files);e.target.value='';}}/></label></div><div className="grid grid-cols-2 sm:grid-cols-3 gap-3">{images.map((im,i)=><div key={`${im.url}-${i}`} className="relative rounded-xl border border-slate-700 overflow-hidden bg-slate-950"><img src={im.url} alt="" className="w-full aspect-square object-contain"/><div className="p-2 flex justify-between gap-1"><button type="button" disabled={i===0} onClick={()=>moveImage(i,-1)} className="px-2 bg-slate-800 rounded">←</button><button type="button" disabled={i===images.length-1} onClick={()=>moveImage(i,1)} className="px-2 bg-slate-800 rounded">→</button><button type="button" onClick={()=>removeImage(i)} className="px-2 bg-rose-950 text-rose-300 rounded">Eliminar</button></div>{i===0&&<span className="absolute top-2 left-2 bg-amber-500 text-slate-950 text-[10px] font-black px-2 py-1 rounded">PORTADA</span>}</div>)}</div></div>
  <div className="flex justify-end gap-2"><button type="button" onClick={()=>setProductOpen(false)} className="px-4 py-2 bg-slate-800 rounded-xl">Cancelar</button><button disabled={busy} className="px-5 py-2 bg-amber-500 text-slate-950 font-black rounded-xl">{busy?'Guardando…':'Guardar y actualizar'}</button></div></form></div>}

  {ticketOpen&&<div className="fixed inset-0 z-50 bg-slate-950/85 p-4 overflow-y-auto"><form onSubmit={saveTicket} className="max-w-xl mx-auto my-8 bg-slate-900 border border-slate-800 rounded-3xl p-6 space-y-4"><div className="flex justify-between"><h3 className="font-black text-lg">{editingTicket?'Modificar pedido':'Ingresar pedido'}</h3><button type="button" onClick={()=>setTicketOpen(false)}>✕</button></div><div className="grid sm:grid-cols-2 gap-3"><select value={ticketForm.origen} onChange={e=>setTicketForm({...ticketForm,origen:e.target.value})} className="bg-slate-800 border border-slate-700 rounded-xl p-3"><option>Web</option><option>WhatsApp</option></select><select value={ticketForm.estado} onChange={e=>setTicketForm({...ticketForm,estado:e.target.value})} className="bg-slate-800 border border-slate-700 rounded-xl p-3">{statuses.map(s=><option key={s}>{s}</option>)}</select><input required value={ticketForm.cliente} onChange={e=>setTicketForm({...ticketForm,cliente:e.target.value})} placeholder="Cliente" className="bg-slate-800 border border-slate-700 rounded-xl p-3"/><input required value={ticketForm.telefono} onChange={e=>setTicketForm({...ticketForm,telefono:e.target.value})} placeholder="Teléfono" className="bg-slate-800 border border-slate-700 rounded-xl p-3"/><input type="number" step="0.01" value={ticketForm.total} onChange={e=>setTicketForm({...ticketForm,total:Number(e.target.value)})} placeholder="Total" className="bg-slate-800 border border-slate-700 rounded-xl p-3 sm:col-span-2"/></div><textarea required rows={4} value={ticketForm.detalle} onChange={e=>setTicketForm({...ticketForm,detalle:e.target.value})} placeholder="Detalle del pedido" className="w-full bg-slate-800 border border-slate-700 rounded-xl p-3"/><textarea rows={2} value={ticketForm.notas_admin} onChange={e=>setTicketForm({...ticketForm,notas_admin:e.target.value})} placeholder="Observaciones internas" className="w-full bg-slate-800 border border-slate-700 rounded-xl p-3"/><div className="flex justify-end gap-2"><button type="button" onClick={()=>setTicketOpen(false)} className="px-4 py-2 bg-slate-800 rounded-xl">Cancelar</button><button disabled={busy} className="px-5 py-2 bg-amber-500 text-slate-950 font-black rounded-xl">{busy?'Guardando…':'Guardar'}</button></div></form></div>}
  </main>;
}
